apiVersion: apps/v1
kind: Deployment
metadata:
  name: blue-deployment
  labels:
    app: django
    version: blue
spec:
  replicas: 3
  selector:
    matchLabels:
      app: django
      version: blue
  template:
    metadata:
      labels:
        app: django
        version: blue
    spec:
      containers:
        - name: django-app
          image: your-dockerhub-username/django-app:2.0
          ports:
            - containerPort: 8000
