pipeline {
    agent any

    environment {
        PYTHONUNBUFFERED = 1
    }

    stages {
        stage('Checkout') {
            steps {
                git branch: 'master',
                    url: 'https://github.com/baye94/alx-backend-python.git'
            }
        }

        stage('Install dependencies') {
            steps {
                dir('messaging_app') {
                    sh 'python3 -m venv venv'
                    sh '. venv/bin/activate && pip3 install -r requirements.txt'
                }
            }
        }

        stage('Run Tests') {
            steps {
                dir('messaging_app') {
                    sh '. venv/bin/activate && pytest --junitxml=report.xml'
                }
            }
        }

        stage('Test Report') {
            steps {
                junit 'messaging_app/report.xml'
            }
        }
    }

    post {
        always {
            cleanWs()
        }
    }
}
