apiVersion: v1
kind: Service
metadata:
  name: django-service
spec:
  selector:
    app: django
    version: green  # Change to 'blue' to switch back
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
  type: ClusterIP
